site_name: Lock-Unlock Documentatie
docs_dir: docs
site_dir: site
site_url: https://kadaster-labs.github.io/lock-unlock-docs/
repo_url: https://github.com/kadaster-labs/lock-unlock-docs
edit_uri: edit/main/docs/
nav:
  - Inleiding: index.md
  - Samenvatting: samenvatting.md
  - Federatieve Bevraging: 
     - federatieve-bevraging/index.md
     - federatieve-bevraging/apis.md
     - federatieve-bevraging/linkeddata.md
     - federatieve-bevraging/informatiekundigekern.md
     - federatieve-bevraging/informatiemodel.md
     - federatieve-bevraging/testopstelling.md
     - federatieve-bevraging/demonstrator.md
     - federatieve-bevraging/conclusies.md
  - Afscherming: 
    - afscherming/index.md
    - afscherming/autorisatie.md
    - afscherming/bestaande-implementaties.md
    - afscherming/afschermingspatronen.md
    - afscherming/oplossingsrichtingen.md
    - afscherming/onderzoeksvoorstel.md
  - Autorisatie als Linked Data:
    - autorisatie-als-linkeddata/index.md
    - autorisatie-als-linkeddata/concept.md
    - autorisatie-als-linkeddata/authorization-ontology.md
    - Implementaties:
      - autorisatie-als-linkeddata/implementaties/index.md
      - autorisatie-als-linkeddata/implementaties/rewrite.md
      - autorisatie-als-linkeddata/implementaties/subgraph.md
    - Demonstrators:
      - autorisatie-als-linkeddata/demonstrators/index.md
      - autorisatie-als-linkeddata/demonstrators/rewrite.md
      - autorisatie-als-linkeddata/demonstrators/subgraph.md
    - autorisatie-als-linkeddata/evaluatie.md   
  - conclusies.md
  - opleveringen.md
  - Achtergrond:
    - achtergrond/index.md
    - achtergrond/glossary.md
    - achtergrond/verwerkingenlogging.md
    - achtergrond/xacml.md
extra_css:
  - css/lock-unlock.css
theme:
  name: material
  palette:
    primary: custom
  language: nl
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant  
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    logo: material/lock
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
